### ISSUE TITLE
Download Button Not Working

### ISSUE THREAD

**Issue by Halal-Face** [EZPlanner/ezplanner-react-client#71]
@virgillee97 Would you mind taking a look at this? 

Steps to reproduce:
Pull changes from master. 
Either type in courses or upload a transcript. 
Download files via the download button.

Result:

![screenshot 51](https://user-images.githubusercontent.com/24881706/53112041-63196880-350c-11e9-8a72-39aeee4c781f.png)

**Comment by virgillee97** [comment]
Lemme take a look when I get home

**Comment by Halal-Face** [comment]
#75
